### ISSUE TITLE
Cannot order books!

### ISSUE THREAD

**Issue by mick1203** [IggyBlob/FHHGB.SEv16.4.SCR.UE.Bookshop#1]
There seems to be a problem with the order process. I can't order any books.

**Comment by IggyBlob** [comment]
Please provide the following information and the steps necessary to reproduce this issue:

- **Apache Version**
- **Browser + Version**
- **OS**

**Comment by mick1203** [comment]
+ **Apache Version**: Apache 2.4.29
+ **Browser + Version**: Firefox 59.0
+ **OS**: Microsoft Windows 10 Enterprise

**Comment by IggyBlob** [comment]
Feature added in fbc7c954
